### ISSUE TITLE
UI bug - add duplicates of one device, pin them all, then refresh the app

### ISSUE THREAD

**Issue by sparks-alec** [stagehacks/Cue-View#46]
looks like all the devices get saved, but during loading, some are deemed duplicates and not added
![Screen Shot 2023-01-05 at 2 40 35 AM](https://user-images.githubusercontent.com/919746/210727672-c90a7daf-f375-4164-9bbb-3b0d9d95a698.png)

**Comment by jwetzell** [comment]
@sparks-alec A place to start would be `device.js` line 28ish.. When devices are registered (which it seems to do when loading them from saved) it skips the 2nd device because of the logic in that section which would skip a device if there already exists a device with that IP address. I assume this is because of that is the same method used by search so it doesn't keep registering the same device over and over from search.

Also I happened to notice in this section use of lodash `_.find` and in general lodash utility functions like find, findIndex, includes, etc. are going to be quite worse performance wise than native JS. And native JS has most of these built in.

**Comment by sparks-alec** [comment]
Yep! totally know where the problem is, just making an issue so I remember to come back to it
